# Generated by Django 2.1.2 on 2018-11-01 05:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CommentSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='DiscussionPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this post', primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=25)),
                ('content', models.CharField(max_length=400)),
                ('comment_section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='UMassApp.CommentSection')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='SurveyPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('question', models.CharField(max_length=200)),
                ('options', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='UMassApp.Choice')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this user across whole platform', primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('user_name', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ['user_name'],
            },
        ),
        migrations.AddField(
            model_name='surveypost',
            name='survey_author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='UMassApp.UserAccount'),
        ),
        migrations.AddField(
            model_name='discussionpost',
            name='disc_author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='UMassApp.UserAccount'),
        ),
        migrations.AddField(
            model_name='commentsection',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='UMassApp.UserAccount'),
        ),
        migrations.AddField(
            model_name='commentsection',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='UMassApp.DiscussionPost'),
        ),
        migrations.AddField(
            model_name='choice',
            name='survey_post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='UMassApp.SurveyPost'),
        ),
    ]
